---
- hosts: localhost
  roles:
 #   - common
  sudo: yes
  
    
  vars:
    http_port: 8081 
    dest: /tmp/pb1/httpd.conf
    max_clients: 200
    socket1: "{{ansible_default_ipv4.address}}:{{ http_port }}"
   
    
    
  vars_files:
    - [ "vars/{{ ansible_distribution.lower() }}.yml" ]  
    
  tasks:
  - name: set http port
    set_fact:
      http_port: 8082
      dest: /tmp/pb1/httpd_u.conf
    when: ansible_distribution != "CentOS"
    
  - name: Display all variables/facts known for a host
    debug: var=socket1
    
  - name: write custom config file
    template: src=templates/custom.j2 dest=/tmp/custom.conf 
    delegate_to: 127.0.0.1
    
    
 
    
#  - name: so long job
#    command: sleep 10
#    async: 12
#    poll: 2
#    register: sleeper
    
   
  - name: create conf33 directory
    file: path=/tmp/pb2 state=directory  
    when: http_port is equalto 8082
  
    
    
    
  

